# Generated by Django 2.2.12 on 2022-08-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco_numero', models.CharField(default='ex: G-36', max_length=7, verbose_name='Bloco e número')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('identidade', models.CharField(max_length=14, verbose_name='CPF ou RG')),
                ('data_de_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('placa_veiculo', models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa do veículo')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('identidade', models.CharField(max_length=14, verbose_name='CPF ou RG')),
                ('data_de_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('placa_veiculo', models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa do veículo')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('data_de_moradia', models.DateField(verbose_name='Morando desde')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Casa')),
            ],
        ),
    ]
