# Generated by Django 2.2.12 on 2022-08-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20220817_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='endereco',
            field=models.CharField(default=1, max_length=300, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
