# Generated by Django 2.2.12 on 2022-08-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_casa_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='bloco_numero',
            field=models.CharField(default='exemplo: G-36', max_length=7, verbose_name='Bloco e número'),
        ),
    ]
