# Generated by Django 2.2.12 on 2022-08-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20220819_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='bloco_numero',
            field=models.CharField(help_text='Exemplo: G-36', max_length=7, verbose_name='Bloco e número'),
        ),
        migrations.AlterField(
            model_name='prestadorservico',
            name='data_de_entrada',
            field=models.DateTimeField(blank=True, help_text='Exemplo: 00/00/0000 19:30', max_length=10, null=True, verbose_name='Data de Entrada/Horário'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='data_de_entrada',
            field=models.DateTimeField(blank=True, help_text='Exemplo: 00/00/0000 19:30', max_length=10, null=True, verbose_name='Data de Entrada/Horário'),
        ),
    ]
