# Generated by Django 2.2.12 on 2022-08-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20220819_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='data_de_moradia',
            field=models.DateField(help_text='Exemplo: 00/00/0000', verbose_name='Morando desde'),
        ),
    ]
