# Generated by Django 2.2.12 on 2022-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20220819_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='data_de_moradia',
            field=models.DateField(help_text='Exemplo: 01/10/1998', verbose_name='Morando desde'),
        ),
        migrations.AlterField(
            model_name='prestadorservico',
            name='data_de_entrada',
            field=models.DateTimeField(blank=True, help_text='Exemplo: 19/08/2022 19:30', max_length=10, null=True, verbose_name='Data de Entrada/Horário'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='data_de_entrada',
            field=models.DateTimeField(blank=True, help_text='Exemplo: 19/08/2022 19:30', max_length=10, null=True, verbose_name='Data de Entrada/Horário'),
        ),
    ]
